name: 3tl Image Build

on:
  push:
    branches: 
      - '**-build'

permissions:
  id-token: write   # This is required for requesting the JWT token
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::059157508967:role/svg-internal-github-oidc-role
      - name: Run 3tl CodeBuild
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: 3tl-build-trigger-imagebuild
          env-vars-for-codebuild: |
            COMMIT_HASH,
            COMMIT_BRANCH,
            COMMIT_REPO,
            COMMIT_USER  
        env:
          COMMIT_HASH: ${{ github.sha }}
          COMMIT_BRANCH: ${{ github.ref_name }}
          COMMIT_REPO: ${{ github.repository }}
          COMMIT_USER: ${{ github.actor }}