name: ECS Image Build

on:
  push:
    branches: 
      - 'build-*'

permissions:
  id-token: write   # This is required for requesting the JWT token
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::${{ vars.PROD_AWS_ACCOUNT_ID }}:role/svg-internal-github-oidc-role
      - name: Run ECS Image Build CodeBuild
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: ${{ env.APPLICATION_NAME }}-ecs-build
          artifacts-type-override: NO_ARTIFACTS
          env-vars-for-codebuild: |
            COMMIT_HASH,
            COMMIT_BRANCH,
            COMMIT_REPO,
            COMMIT_USER,
            APPLICATION_NAME,
            RUNTIME,
            BUILDSPEC,
            RUNTIME_VERSION,
            INGRESS_LEVEL,
            STICKY_SESSIONS,
            HEALTH_CHECK_PATH
        env:
          COMMIT_HASH: ${{ github.sha }}
          COMMIT_BRANCH: ${{ github.ref_name }}
          COMMIT_REPO: ${{ github.repository }}
          COMMIT_USER: ${{ github.actor }}
          APPLICATION_NAME: <APPLICATIONNAME>
          
          # RUNTIME - The AWS CodeBuild docker image to use. This affects what runtimes you may select.
          #   Please consult the runtime version compatibility matrix before makinga selection:
          #   https://docs.aws.amazon.com/codebuild/latest/userguide/available-runtimes.html
          #   Or just use the latest

          #   AllowedValues:
          #   - amazonlinux2-x86_64-standard:5.0
          #   - amazonlinux2-x86_64-standard:4.0
          #   - amazonlinux2-x86_64-standard:3.0
          #   - standard:3.0
          RUNTIME: <CODEBUILDCONTAINER>

          # BUILDSPEC - The buildspect to run in the CodeBuild.
          #  AllowedValues:
          # - dip-app_specific
          # - dip-java-mvn
          # - dip-java-gradle
          # - dip-java-tomee
          # - dip-node6
          # - dip-node10
          # - dip-node16
          # - dip-node18
          # - dip-node20
          # - dip-node18-npm
          # - dip-node20-npm
          # - dip-python3
          BUILDSPEC: <BUILDSPEC>

          #  RUNTIME_VERSION - The runtime versions the AWS Codebuild to use.
          #   Please consult the runtime version compatibility matrix before makinga selection:
          #   https://docs.aws.amazon.com/codebuild/latest/userguide/available-runtimes.html
          # 
          #  Java AllowedValues:
          #    - corretto8
          #    - corretto11
          #    - corretto17
          #    - corretto21
          #  NodeJS AllowedValues:
          #   - 10
          #   - 12
          #   - 16
          #   - 18
          #   - 20
          #  Python AllowedValues:
          #   - 3.8
          #   - 3.9
          #   - 3.10
          #   - 3.11
          #  Docker AllowedValues:
          #   - 18
          RUNTIME_VERSION: <RUNTIMEVERSION>

          # INGRESS_LEVEL - The level of ingress to allow to the service.
          #   AllowedValues:
          #     - Internal
          #     - Partner
          #     - Public
          INGRESS_LEVEL: 'Internal'

          # STICKY_SESSIONS - Turns on sticky sessions for the trget group.
          #   AllowedValues:
          #    - true
          #    - false
          STICKY_SESSIONS: 'false'

          HEALTH_CHECK_PATH: '/health'
          
          