name: Snyk-Container-Monitor-Scan     

on:
  pull_request:
    branches: 
      - <TARGET_BRANCH> # Replace <TARGET_BRANCH> with the branch you want to target, e.g., 'dev01' or 'main'
env:
  APP_NAME: test-app

permissions:
  id-token: write   
  contents: read

jobs:
  snyk-container-scan:
    runs-on:
      - codebuild-gh-runner-org-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: get repo
        uses: actions/checkout@v4 
      - name: get ecr creds
        run: aws ecr get-login-password  | docker login -u AWS --password-stdin https://059157508967.dkr.ecr.us-west-2.amazonaws.com
      - name: docker build
        run: docker build . -t $APP_NAME
      - name: Snyk scan for showing results on Gh Workflow 
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: $APP_NAME
          args: "--file=Dockerfile --severity-threshold=high"
      - name: Snyk Monitor to send logs to Snyk UI
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: $APP_NAME
          args: "--file=Dockerfile --severity-threshold=high"
          command: monitor
        
  trigger-stackhawk:
    needs: snyk-container-scan
    uses: ./.github/workflows/<STACKHAWK_SCAN_WORKFLOW_YAML_FILE>  #Replace STACKHAWK_SCAN_WORKFLOW_YAML_FILE with the name of stackahwk workflow file that you choosed for a runtime.
    secrets: inherit
    permissions:
      contents: read
      pull-requests: write