name: Snyk-lambda-scan-typescript/javascript       

on:
  pull_request:
    branches: 
      - <TARGET_BRANCH>  # Replace <TARGET_BRANCH> with the branch you want to target, e.g., 'dev01' or 'main'

env:
  TEMPLATE_FILE: template.yml  # Specify your AWS SAM template file
  ORG_ID: <ORG-ID> #Replace with your Snyk organization ID

permissions:
  id-token: write   
  contents: read

jobs:
  snyk_scan:
    runs-on: codebuild-gh-runner-org-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run Snyk Code Security Scan
        uses: snyk/actions/node@master 
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }} 
        with:
          args: --severity-threshold=high --org=$ORG_ID
          command: monitor
      - name: Run Snyk IaC Scan for AWS SAM Templates
        uses: snyk/actions/iac@master  
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          file: $TEMPLATE_FILE  # Use the environment variable for the template file      
          args: --report --severity-threshold=high --org=$ORG_ID
