name: Stackhawk DAST

on:
  workflow_call:
    secrets:
      HAWK_API_KEY:
        required: true

env:
  APP_HEALTH_CHECK_URL: https://localhost:8080/health
  APP_NAME: java-app
  CONTAINER_NAME: java-container

jobs:
  build-image:
    runs-on:
      - codebuild-gh-runner-org-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: get repo
        uses: actions/checkout@v4
      - name: set up java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: get ecr creds
        run: aws ecr get-login-password  | docker login -u AWS --password-stdin https://059157508967.dkr.ecr.us-west-2.amazonaws.com
      - name: Run the Maven install
        run: mvn install -q
      - name: Image build
        run: docker build -t java-app .
      - name: docker run
        run: >
          docker run -d -p 8080:8080
          --rm
          --name $CONTAINER_NAME
          --network host
          -e AWS_DEFAULT_REGION
          -e AWS_CONTAINER_CREDENTIALS_RELATIVE_URI
          -e Environment=dev01
          $APP_NAME
      - name: Adding delay
        run: sleep 10   
      - name: check app running
        run: | 
          for i in {1..5}; do 
            if curl -kIs $APP_HEALTH_CHECK_URL | grep 200; then
              exit 0 
            else
              sleep 10
            fi
          done
          docker logs java-container
          exit 1
      - name: Run HawkScan
        id: hawkscan
        uses: stackhawk/hawkscan-action@v2
        with:
          apiKey: ${{ secrets.HAWK_API_KEY }}
        env:
          COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
          BRANCH_NAME: ${{ github.head_ref }}