name: Stackhawk DAST Java

on:
  pull_request:
    branches: 
      - <TRIGGER_BRANCH>
  # pull_request:
  #   types: [opened, assigned, unassigned ]

permissions:
  id-token: write   # This is required for requesting the JWT token
  contents: read

jobs:
  build-image:
    runs-on:
      - codebuild-gh-runner-org-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: get repo
        uses: actions/checkout@v4
      - name: set up java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: get ecr creds
        run: aws ecr get-login-password  | docker login -u AWS --password-stdin https://059157508967.dkr.ecr.us-west-2.amazonaws.com
      - name: Run the Maven Clean install
        run: mvn install -q
      - name: Image build
        run: docker build -t <IMAGE_NAME> .
      - name: docker run
        run: >
          docker run -d -p 8080:8080
          --rm
          --name <CONTAINER_NAME>
          -e AWS_DEFAULT_REGION
          -e AWS_CONTAINER_CREDENTIALS_RELATIVE_URI
          -e Environment=dev01
           <IMAGE_NAME>
      - name: Adding delay
        run: sleep 10   
      - name: check app running
        run: while ! curl -kIs https://localhost:8080/hello | grep 200; do sleep 10; echo waiting...; done
      - name: Run HawkScan
        id: hawkscan
        uses: stackhawk/hawkscan-action@v2
        with:
          apiKey: ${{ secrets.HAWK_API_KEY }}
        env:
          COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
          BRANCH_NAME: ${{ github.head_ref }}

  close-pr-on-failure:
      runs-on: codebuild-gh-runner-org-${{ github.run_id }}-${{ github.run_attempt }}
      permissions:
        contents: read
        pull-requests: write
      needs: build-image
      if: failure() && github.event_name == 'pull_request'

      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Close PR on Failure
          run: gh pr close "${{ github.event.pull_request.number }}" --comment "This pull request was automatically closed because the Stackhawk scan found vulnerabilities"
          env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
