name: Stackhawk DAST

on:
  workflow_call:
    secrets:
      HAWK_API_KEY:
        required: true

env:
  APP_HEALTH_CHECK_URL: https://localhost:8080/health

jobs:
  stackhawk-dast:
    runs-on:
      - codebuild-gh-runner-org-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: get repo
        uses: actions/checkout@v4
      - name: set up java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
      - name: get ecr creds
        run: aws ecr get-login-password  | docker login -u AWS --password-stdin https://059157508967.dkr.ecr.us-west-2.amazonaws.com
      - name: docker build
        run: docker build . -t node-python-app
      - name: docker run
        run: >
          docker run -d --rm -p 8080:8080
          --name node-python-container
          --network host 
          -e AWS_DEFAULT_REGION
          -e AWS_CONTAINER_CREDENTIALS_RELATIVE_URI
          -e Environment=dev01
          node-python-app
      - name: check app running
        run: | 
          for i in {1..5}; do 
            if curl -kIs $APP_HEALTH_CHECK_URL | grep 200; then
              exit 0 
            else
              sleep 10
            fi
          done
          docker logs node-python-container
          exit 1
      - name: Run HawkScan
        id: hawkscan
        uses: stackhawk/hawkscan-action@v2
        with:
          apiKey: ${{ secrets.HAWK_API_KEY }}
        env:
          COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
          BRANCH_NAME: ${{ github.head_ref }}
